# Generated by Django 4.2.16 on 2024-11-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('proveedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('gaseosa', 'Gaseosa'), ('alcoholica', 'Alcohólica')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('volumen', models.IntegerField()),
                ('contenido_alcoholico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.loteproducto')),
            ],
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto'),
        ),
    ]
